#!/bin/bash

mkpackage() {
    pkg_url=$1
    pkg=`echo $pkg_url | cut -d'/' -f5`
    runuser -u xundao -- bash -c "cd local_repo && git clone $pkg_url $pkg && (cd $pkg && makepkg -s -f --noconfirm)"
}

pacman -S --noconfirm base-devel

useradd -m -s /bin/bash -g wheel xundao
sed -E -i '/^#\s*%wheel.*NOPASSWD/{s/^#\s*//}' /etc/sudoers

mkdir -p local_repo && chmod 777 -R local_repo
pkgs=(
    https://gitee.com/xundaoxd/dwm
    https://aur.archlinux.org/zfs-linux.git
)
for pkg in ${pkgs[@]}; do
    mkpackage $pkg
done

for p in `find local_repo -type f -name "*.zst"`; do
    mv $p local_repo
    repo-add local_repo/custom.db.tar.gz local_repo/`basename $p`;
done

cat > ./configs/pacman.conf << EOF
[options]
HoldPkg     = pacman glibc
Architecture = auto
ParallelDownloads = 5

SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

[custom]
SigLevel = Optional TrustAll
Server = file:///${PWD}/local_repo
EOF


