name: Build archiso on arch
on: workflow_dispatch

jobs:
  build-archiso:
    name: Build the iso
    runs-on: ubuntu-latest
    steps:
      - uses: RangHo/setup-arch@main
        with:
          version: latest
          mirror: https://geo.mirror.pkgbuild.com
          packages: "arch-install-scripts awk dosfstools e2fsprogs erofs-utils findutils grub gzip libarchive libisoburn mtools openssl pacman sed squashfs-tools"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Perform a Pester test from the command-line
        shell: arch.sh {0}
        run: cat /etc/os-release
