name: ci

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - uses: actions/checkout@v3
      - run: |
          pacman -Syy
          pacman -S --noconfirm archiso git
          mkdir -p work out
          mkarchiso -w work -o out ./configs/baseline/
      - uses: actions/upload-artifact@v3
        with:
          name: archiso
          path: out/

