name: ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - run: |
          pacman -Syy
          pacman -S --noconfirm archiso git
          ./mkrepo
          mkdir -p work out
          ./mkarchiso -v -w work -o out ./configs/
      - uses: actions/upload-artifact@v3
        with:
          name: archiso
          path: out/

